name: Hello

on: push

jobs:
    primeiro_job:
        runs-on: ubuntu-latest
        env:
            GREETING_MESSAGE: That's is bro!
        steps:
            - name: Welcome Message
              run: echo $GREETING_MESSAGE