name: Hello

on: push

jobs:
    initial_job:
        runs-on: ubuntu-latest
        steps:
            - name: Welcome Message
              run: echo ${{vars.GREETING_MESSAGE}}
            
            - name: Login with Username and Password
              run: echo login with username=${{vars.ACCOUNT_USERNAME}}and password=${{secrets.ACCOUNT_PASSWORD}}

    file_job:
        runs-on: ubuntu-latest
        steps:
            # - name: Checkout Repository
            #   uses: actions/checkout@v4
            
            - name: Write File
              run: echo "Let's do this!" >> lets.txt

            - name: Read File
              run: cat ./lets.txt