name: Hello

on: push

jobs:
    primeiro_job:
        runs-on: ubuntu-latest
        steps:
            - name: Welcome Message
              run: echo ${{vars.GREETING_MESSAGE}}
            
            - name: Login with Username and Password
              run: echo login with username=${{vars.ACCOUNT_USERNAME}}and password=${{secrets.ACCOUNT_PASSWORD}}