name: Hello

on: push

jobs:
    initial_job:
        runs-on: ubuntu-latest
        steps:
            - name: Welcome Message
              run: echo ${{vars.GREETING_MESSAGE}}
            
            - name: Login with Username and Password
              run: echo login with username=${{vars.ACCOUNT_USERNAME}}and password=${{secrets.ACCOUNT_PASSWORD}}

    file_job_virtual_level:
        runs-on: ubuntu-latest
        steps: 
            - name: Write File
              run: echo "Let's do this!" >> lets.txt

            - name: Read File
              run: cat ./lets.txt

            - name: List All Files
              run: ls -ltra
    file_job_repository_level:
        runs-on: ubuntu-latest
        steps:
            - name: Read REAME.md File
              run: cat README.md

