name: Hello

on: push

jobs:
    primeiro_job:
        runs-on: ubuntu-latest
        steps:
            - name: Welcome Message
              env:
                GREETING_MESSAGE: Greetings, my friend!
              run: echo $GREETING_MESSAGE