name: Hello

on: push

jobs:
    primeiro_job:
        runs-on: ubuntu-latest
        steps:
            - name: Welcome Message
              run: echo ${{env.GREETING_MESSAGE}}
            
            - name: Login with Username and Password
              run: echo login with username=${{env.ACCOUNT_USERNAME}}and password=${{secrets.ACCOUNT_PASSWORD}}